
apiVersion: v1
kind: Service
metadata:
  labels:
    app: authservice
  name: authservice
spec:
  ports:
  - name: web
    port: 8888
    targetPort: 8888
  - name: drpc
    port: 6666
    targetPort: 6666
  selector:
    app: authservice
