
apiVersion: v1
kind: ConfigMap
metadata:
  name: storagenode
data:
  STORJ_CONSOLE_STATIC_DIR: /var/lib/storj/web/storagenode
  STORJ_DEBUG_ADDR: 0.0.0.0:11111
  STORJ_DEFAULTS: dev
  STORJ_IDENTITY_DIR: /var/lib/storj/.local/share/storj/identity/storagenode/
  STORJ_LOG_LEVEL: debug
  STORJ_METRICS_APP_SUFFIX: sim
  STORJ_OPERATOR_EMAIL: storage9@mail.test
  STORJ_OPERATOR_WALLET: 0x0123456789012345678901234567890123456789
  STORJ_ROLE: storagenode
  STORJ_SERVER_EXTENSIONS_REVOCATION: "false"
  STORJ_SERVER_USE_PEER_CA_WHITELIST: "false"
  STORJ_STORAGE2_MONITOR_MINIMUM_DISK_SPACE: "0"
  STORJ_STORAGE2_TRUST_SOURCES: 12whfK1EDvHJtajBiAUeajQLYcWqxcQmdYQU5zX5cCf6bAxfgu4@satellite-api:7777
  STORJ_STORAGE_ALLOCATED_DISK_SPACE: 1G
  STORJ_VERSION_SERVER_ADDRESS: http://versioncontrol:8080/
  STORJ_WAIT_FOR_SATELLITE: "true"
