apiVersion: v1
kind: ConfigMap
metadata:
  name: satellite-api
data:
      STORJ_ADDRESS: 0.0.0.0:7777
      STORJ_CONSOLE_ADDRESS: 0.0.0.0:10000
      STORJ_CONSOLE_AUTH_TOKEN_SECRET: my-suppa-secret-key
      STORJ_CONSOLE_GATEWAY_CREDENTIALS_REQUEST_URL: http://localhost:8888
      STORJ_CONSOLE_LINKSHARING_URL: http://localhost:9090
      STORJ_CONSOLE_OPEN_REGISTRATION_ENABLED: "true"
      STORJ_CONSOLE_RATE_LIMIT_BURST: "100"
      STORJ_CONSOLE_STATIC_DIR: /var/lib/storj/storj/web/satellite/
      STORJ_DATABASE: cockroach://root@cockroach-0.cockroach.default.svc.cluster.local:26257/master?sslmode=disable
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_DEFAULTS: dev
      STORJ_IDENTITY_DIR: /var/lib/storj/identities/1
      STORJ_LIVE_ACCOUNTING_STORAGE_BACKEND: redis://redis-0.redis.default.svc.cluster.local:6379?db=0
      STORJ_LOG_LEVEL: debug
      STORJ_MAIL_FROM: Storj <yaroslav-satellite-test@storj.io>
      STORJ_MAIL_SMTP_SERVER_ADDRESS: smtp.gmail.com:587
      STORJ_MAIL_TEMPLATE_PATH: /var/lib/storj/storj/web/satellite/static/emails/
      STORJ_METAINFO_DATABASE_URL: cockroach://root@cockroach-0.cockroach.default.svc.cluster.local:26257/metainfo?sslmode=disable
      STORJ_METAINFO_RATE_LIMITER_ENABLED: "false"
      STORJ_METRICS_APP_SUFFIX: sim
      STORJ_ORDERS_ENCRYPTION_KEYS: 0100000000000000=0100000000000000000000000000000000000000000000000000000000000000
      STORJ_ROLE: satellite-api
      STORJ_SERVER_ADDRESS: satellite-api-0.satellite-api.default.svc.cluster.local:7777
      STORJ_SERVER_EXTENSIONS_REVOCATION: "false"
      STORJ_SERVER_REVOCATION_DBURL: redis://redis-0.svc.cluster.local:6379?db=1
      STORJ_SERVER_USE_PEER_CA_WHITELIST: "false"
      STORJ_WAIT_FOR_DB: "true"