apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: storagenode
  name: storagenode
spec:
  serviceName: storagenode
  replicas: 10
  selector:
    matchLabels:
      app: storagenode
  template:
    metadata:
      labels:
        app: storagenode
    spec:
      containers:
        - args:
            - storagenode
            - run
            - --defaults=dev
          envFrom:
            - configMapRef:
                name: storagenode
       
          image: ghcr.io/elek/storj:1.45.3
          name: storagenode
          ports:
            - containerPort: 7777
            - containerPort: 10000
          resources: {}
      restartPolicy: Always

