apiVersion: v1
kind: Service
metadata:
  labels:
    app: storagenode
  name: storagnode
spec:
  ports:
    - name: "7777"
      port: 7777
      targetPort: 7777
    - name: "10000"
      port: 10000
      targetPort: 10000
  selector:
    app: storagenode
status:
  loadBalancer: {}
